# http://module-build.sourceforge.net/META-spec-v1.3.html 
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#

name: Log-Fine
version: 0.20
version_from: lib/Log/Fine.pm
author: Christopher M. Fuhrman <cfuhrman@panix.com>
license: bsd
distribution_type: module
required:
  Sys::Syslog: 0.13
recommends:
  Test::Output: 0.10
  Pod::Coverage: 0.19
  Test::Pod: 1.14
meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: hand

