#!perl -T

#
# $Id$
#

use Test::Simple tests => 8;

use File::Basename;
use Log::BSDLog;
use Log::BSDLog::Handle::Syslog;
use Sys::Syslog qw( :standard :macros );

{

    my $msg = "This is a test message generated by the install of Log::BSDLog";

    # get a logger
    my $log = Log::BSDLog->getLogger("handlesyslog0");

    ok(ref $log eq "Log::BSDLog::Logger");

    # add a handle.  Note we use the default formatter.
    my $handle = Log::BSDLog::Handle::Syslog->new();

    # do some validation
    ok($handle->isa("Log::BSDLog::Handle"));

    # these should be set to their default values
    ok($handle->{mask} == Log::BSDLog::Handle->DEFAULT_LOGMASK);
    ok($handle->{level} == DEBG);
    ok($handle->{formatter}->isa("Log::BSDLog::Formatter::Basic"));

    # Syslog-specific attributes
    ok($handle->{ident} eq basename $0);
    ok($handle->{logopts} =~ /pid/);
    ok($handle->{facility} == LOG_LOCAL0);

    # write a test message
    $handle->msgWrite(INFO, $msg, 1);

}
